spring:
  datasource:
    framework:
      url: jdbc:h2:mem:main;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      username: sa
      password:
      hikari:
        maximum-pool-size: 30
    main:
      url: jdbc:h2:mem:main;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      username: sa
      password:
    external:
      url: jdbc:h2:mem:external;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
      username: sa
      password:
